### ISSUE TITLE
[Question ]How did you manage to remove the junk?

### ISSUE THREAD

**Issue by spatrickapps** [benmel/Wikivoyage#17]
I'm looking over the code but i cant figure out how you remove all of the junk from the html text.

https://en.wikivoyage.org/w/api.php?action=parse&disableeditsection=&format=json&mobileformat=&noimages=&pageid=6850&prop=text

It returns the html with a bunch of junk like.

`\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n 
The Mustard Seed,\u00a01970 Maybank Hwy,\u00a0\u260e +1 843 762-0072
`

**Comment by benmel** [comment]
Hi @spatrickapps, sorry for the late response.

I looked into it and the app doesn't remove the newlines or any other characters that are returned in the text from the API. If you look [here](https://github.com/benmel/Wikivoyage/blob/master/Wikivoyage/OfflineWebViewController.swift#L33) what the offline web view does is it loads a string that contains the HTML string returned from the API. The newlines will just affect the HTML itself, but won't be visible in the web view.

If you still want to remove specific characters you can do something like: `html.stringByReplacingOccurrencesOfString("\n", withString: "")`. The characters that are preceded with `\u` are unicode characters that will be properly displayed in a web view. I believe `\u00a0` is a space and `\u260e` is a telephone symbol. I hope that helps.
